In [43]:
import numpy as np
import pandas as pd
import tqdm

df = pd.read_csv("/opt/ml/input/data/train_test_data.csv")
df = df.sort_values(by=["userID", "Timestamp"]).reset_index(drop=True)

df

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag
0,0,A060001001,A060000001,1,2020-03-24 00:17:11,7224
1,0,A060001002,A060000001,1,2020-03-24 00:17:14,7225
2,0,A060001003,A060000001,1,2020-03-24 00:17:22,7225
3,0,A060001004,A060000001,1,2020-03-24 00:17:29,7225
4,0,A060001005,A060000001,1,2020-03-24 00:17:36,7225
...,...,...,...,...,...,...
2525951,7441,A030071005,A030000071,0,2020-06-05 06:50:21,438
2525952,7441,A040165001,A040000165,1,2020-08-21 01:06:39,8836
2525953,7441,A040165002,A040000165,1,2020-08-21 01:06:50,8836
2525954,7441,A040165003,A040000165,1,2020-08-21 01:07:36,8836
2525955,7441,A040165004,A040000165,1,2020-08-21 01:08:49,8836

In [77]:
from datetime import date
test = pd.read_csv("/opt/ml/input/data/test_data.csv")
test = test.sort_values(by=["userID", "Timestamp"]).reset_index(drop=True)

def fe(df):
    df['month'] = df.Timestamp.str[5:7]
    df['hour'] = df.Timestamp.str[11:13]

    yy = df.Timestamp.str[:4]
    mm = df.Timestamp.str[5:7]
    dd = df.Timestamp.str[8:10]

    y = [int(y) for y in list(yy)]
    m = [int(m) for m in list(mm)]
    d = [int(d) for d in list(dd)]

    df['week'] = [date(i,j,k).weekday() for i,j,k in zip(y,m,d)]

    df.to_csv('../../../data/train.csv', index=False)

    df = pd.read_csv('../../../data/train.csv', parse_dates=['Timestamp'])
    df = df.sort_values(by=['userID', 'Timestamp']).reset_index(drop=True)

    diff = df.loc[:, ['userID', 'Timestamp']].groupby('userID').diff().fillna(pd.Timedelta(seconds=0))
    diff = diff.fillna(pd.Timedelta(seconds=0))
    diff = diff['Timestamp'].apply(lambda x: x.total_seconds())

    df['elapsed'] = diff

    df["elapsed"] = df["elapsed"].apply(
        lambda x: x if x < 600 and x >= 0 else 0)

    def elap(x):
        if x == 0:
            return 0
        elif x < 9:
            return 1
        elif x < 101:
            return 2
        elif x < 201:
            return 3
        elif x < 301:
            return 4
        elif x < 401:
            return 5
        elif x < 501:
            return 6
        elif x < 601:
            return 7

    df['elapsed_cate'] = df.elapsed.apply(lambda x : elap(x))
    
    df['assessmentItemID0'] = df['assessmentItemID'].str[2]
    df['assessmentItemID1'] = df['assessmentItemID'].str[4:7]
    df['assessmentItemID2'] = df['assessmentItemID'].str[8:10]

    df['testId0'] = df['testId'].str[2]
    df['testId1'] = df['testId'].str[7:10]
    
    return df
    
test = fe(test)
test

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,elapsed,elapsed_cate,assessmentItemID0,assessmentItemID1,assessmentItemID2,testId0,testId1
0,3,A050023001,A050000023,1,2020-01-09 10:56:31,2626,1,10,3,0.0,0,5,023,01,5,023
1,3,A050023002,A050000023,1,2020-01-09 10:56:57,2626,1,10,3,26.0,2,5,023,02,5,023
2,3,A050023003,A050000023,0,2020-01-09 10:58:31,2625,1,10,3,94.0,2,5,023,03,5,023
3,3,A050023004,A050000023,0,2020-01-09 10:58:36,2625,1,10,3,5.0,1,5,023,04,5,023
4,3,A050023006,A050000023,0,2020-01-09 10:58:43,2623,1,10,3,7.0,1,5,023,06,5,023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260109,7439,A040130001,A040000130,0,2020-10-14 23:07:23,8832,10,23,2,0.0,0,4,130,01,4,130
260110,7439,A040130002,A040000130,1,2020-10-14 23:07:41,8832,10,23,2,18.0,2,4,130,02,4,130
260111,7439,A040130003,A040000130,1,2020-10-14 23:08:02,8244,10,23,2,21.0,2,4,130,03,4,130
260112,7439,A040130004,A040000130,1,2020-10-14 23:09:31,8244,10,23,2,89.0,2,4,130,04,4,130
260113,7439,A040130005,A040000130,-1,2020-10-14 23:10:03,8832,10,23,2,32.0,2,4,130,05,4,130

In [44]:
from datetime import date
df['month'] = df.Timestamp.str[5:7]
df['hour'] = df.Timestamp.str[11:13]

yy = df.Timestamp.str[:4]
mm = df.Timestamp.str[5:7]
dd = df.Timestamp.str[8:10]

y = [int(y) for y in list(yy)]
m = [int(m) for m in list(mm)]
d = [int(d) for d in list(dd)]

df['week'] = [date(i,j,k).weekday() for i,j,k in zip(y,m,d)]

df.to_csv('../../../data/train.csv', index=False)

df = pd.read_csv('../../../data/train.csv', parse_dates=['Timestamp'])
df = df.sort_values(by=['userID', 'Timestamp']).reset_index(drop=True)

diff = df.loc[:, ['userID', 'Timestamp']].groupby('userID').diff().fillna(pd.Timedelta(seconds=0))
diff = diff.fillna(pd.Timedelta(seconds=0))
diff = diff['Timestamp'].apply(lambda x: x.total_seconds())

df['elapsed'] = diff

df["elapsed"] = df["elapsed"].apply(
    lambda x: x if x < 600 and x >= 0 else 0)

def elap(x):
    if x == 0:
        return 0
    elif x < 9:
        return 1
    elif x < 101:
        return 2
    elif x < 201:
        return 3
    elif x < 301:
        return 4
    elif x < 401:
        return 5
    elif x < 501:
        return 6
    elif x < 601:
        return 7
    
df['elapsed_cate'] = df.elapsed.apply(lambda x : elap(x))

In [45]:
df['assessmentItemID0'] = df['assessmentItemID'].str[2]
df['assessmentItemID1'] = df['assessmentItemID'].str[4:7]
df['assessmentItemID2'] = df['assessmentItemID'].str[8:10]

df['testId0'] = df['testId'].str[2]
df['testId1'] = df['testId'].str[7:10]

In [46]:
correct_t = df.groupby(["testId0"])["answerCode"].agg(["mean", "std"])
correct_t.columns = ["test0_mean", "test0_std"]
correct_t1 = df.groupby(["testId1"])["answerCode"].agg(["mean", "std"])
correct_t1.columns = ["test1_mean", "test1_std"]

correct_k = df.groupby(["KnowledgeTag"])["answerCode"].agg(["mean", "std"])
correct_k.columns = ["tag_mean", "tag_std"]

correct_a = df.groupby(["assessmentItemID0"])["answerCode"].agg(["mean", "std"])
correct_a.columns = ["ass0_mean", "ass0_std"]
correct_a1 = df.groupby(["assessmentItemID1"])["answerCode"].agg(["mean", "std"])
correct_a1.columns = ["ass1_mean", "ass1_std"]
correct_a2 = df.groupby(["assessmentItemID2"])["answerCode"].agg(["mean", "std"])
correct_a2.columns = ["ass2_mean", "ass2_std"]

df = pd.merge(df, correct_t, on=["testId0"], how="left")
df = pd.merge(df, correct_t1, on=["testId1"], how="left")
df = pd.merge(df, correct_k, on=["KnowledgeTag"], how="left")
df = pd.merge(df, correct_a, on=["assessmentItemID0"], how="left")
df = pd.merge(df, correct_a1, on=["assessmentItemID1"], how="left")
df = pd.merge(df, correct_a2, on=["assessmentItemID2"], how="left")

In [78]:
test = pd.merge(test, correct_t, on=["testId0"], how="left")
test = pd.merge(test, correct_t1, on=["testId1"], how="left")
test = pd.merge(test, correct_k, on=["KnowledgeTag"], how="left")
test = pd.merge(test, correct_a, on=["assessmentItemID0"], how="left")
test = pd.merge(test, correct_a1, on=["assessmentItemID1"], how="left")
test = pd.merge(test, correct_a2, on=["assessmentItemID2"], how="left")

test

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,elapsed,...,test1_mean,test1_std,tag_mean,tag_std,ass0_mean,ass0_std,ass1_mean,ass1_std,ass2_mean,ass2_std
0,3,A050023001,A050000023,1,2020-01-09 10:56:31,2626,1,10,3,0.0,...,0.613659,0.486924,0.636571,0.481124,0.659098,0.474013,0.613659,0.486924,0.749694,0.433190
1,3,A050023002,A050000023,1,2020-01-09 10:56:57,2626,1,10,3,26.0,...,0.613659,0.486924,0.636571,0.481124,0.659098,0.474013,0.613659,0.486924,0.720312,0.448847
2,3,A050023003,A050000023,0,2020-01-09 10:58:31,2625,1,10,3,94.0,...,0.613659,0.486924,0.663200,0.472710,0.659098,0.474013,0.613659,0.486924,0.688360,0.463164
3,3,A050023004,A050000023,0,2020-01-09 10:58:36,2625,1,10,3,5.0,...,0.613659,0.486924,0.663200,0.472710,0.659098,0.474013,0.613659,0.486924,0.663597,0.472479
4,3,A050023006,A050000023,0,2020-01-09 10:58:43,2623,1,10,3,7.0,...,0.613659,0.486924,0.570222,0.495099,0.659098,0.474013,0.613659,0.486924,0.556891,0.496754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260109,7439,A040130001,A040000130,0,2020-10-14 23:07:23,8832,10,23,2,0.0,...,0.608201,0.488169,0.638385,0.480557,0.680256,0.466378,0.608201,0.488169,0.749694,0.433190
260110,7439,A040130002,A040000130,1,2020-10-14 23:07:41,8832,10,23,2,18.0,...,0.608201,0.488169,0.638385,0.480557,0.680256,0.466378,0.608201,0.488169,0.720312,0.448847
260111,7439,A040130003,A040000130,1,2020-10-14 23:08:02,8244,10,23,2,21.0,...,0.608201,0.488169,0.765442,0.423899,0.680256,0.466378,0.608201,0.488169,0.688360,0.463164
260112,7439,A040130004,A040000130,1,2020-10-14 23:09:31,8244,10,23,2,89.0,...,0.608201,0.488169,0.765442,0.423899,0.680256,0.466378,0.608201,0.488169,0.663597,0.472479
260113,7439,A040130005,A040000130,-1,2020-10-14 23:10:03,8832,10,23,2,32.0,...,0.608201,0.488169,0.638385,0.480557,0.680256,0.466378,0.608201,0.488169,0.599375,0.490026

In [79]:
def fe2(df):
    df["user_correct_answer"] = (
        df.groupby("userID")["answerCode"]
        .transform(lambda x: x.cumsum().shift(1))
        .fillna(0)
    )
    df["user_total_answer"] = df.groupby("userID")["answerCode"].cumcount() + 1
    df["user_acc"] = (df["user_correct_answer"] / df["user_total_answer"])
    return df

test = fe2(test)

In [80]:
test2[['userID','user_correct_answer', 'user_acc', 'user_total_answer', 'answerCode']].tail(25)

        userID  user_correct_answer  user_acc  user_total_answer  answerCode
260089    7417                  0.0  0.000000                  7           0
260090    7417                  0.0  0.000000                  8           0
260091    7417                  0.0  0.000000                  9           0
260092    7417                  0.0  0.000000                 10           0
260093    7417                  0.0  0.000000                 11           0
260094    7417                  0.0  0.000000                 12           1
260095    7417                  1.0  0.076923                 13           1
260096    7417                  2.0  0.142857                 14           0
260097    7417                  2.0  0.133333                 15          -1
260098    7439                  0.0  0.000000                  1           1
260099    7439                  1.0  0.500000                  2           1
260100    7439                  2.0  0.666667                  3           1
260101    7439                  3.0  0.750000                  4           1
260102    7439                  4.0  0.800000                  5           0
260103    7439                  4.0  0.666667                  6           1
260104    7439                  5.0  0.714286                  7           1
260105    7439                  6.0  0.750000                  8           1
260106    7439                  7.0  0.777778                  9           0
260107    7439                  7.0  0.700000                 10           0
260108    7439                  7.0  0.636364                 11           1
260109    7439                  8.0  0.666667                 12           0
260110    7439                  8.0  0.615385                 13           1
260111    7439                  9.0  0.642857                 14           1
260112    7439                 10.0  0.666667                 15           1
260113    7439                 11.0  0.687500                 16          -1

In [51]:
df["user_correct_answer"] = (
    df.groupby("userID")["answerCode"]
    .transform(lambda x: x.cumsum().shift(1))
    .fillna(0)
)
df["user_total_answer"] = df.groupby("userID")["answerCode"].cumcount() + 1
df["user_acc"] = (df["user_correct_answer"] / df["user_total_answer"])

In [52]:
df['recAccuracy'] = -1

group = df.groupby("userID")

def set_rec_count(group):
    group.sort_values(by='Timestamp', axis=0, inplace=True)
    recAccuracy = group['answerCode'].rolling(10, min_periods=1).sum().shift(1)
    group['recCount'] = recAccuracy
    
    return group

df['recCount'] = 0

group = df.groupby("userID")

group = group.apply(set_rec_count)
group.reset_index(drop=True, inplace=True)

df['recCount'] = group['recCount']
df['recCount']= df['recCount'].fillna(0)
df['recCount'] = df['recCount'].astype(int)
df.head(10)

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,elapsed,...,ass0_std,ass1_mean,ass1_std,ass2_mean,ass2_std,user_correct_answer,user_total_answer,user_acc,recAccuracy,recCount
0,0,A060001001,A060000001,1,2020-03-24 00:17:11,7224,3,0,1,0.0,...,0.452701,0.708478,0.454477,0.749694,0.433190,0.0,1,0.000000,-1,0
1,0,A060001002,A060000001,1,2020-03-24 00:17:14,7225,3,0,1,3.0,...,0.452701,0.708478,0.454477,0.720312,0.448847,1.0,2,0.500000,-1,1
2,0,A060001003,A060000001,1,2020-03-24 00:17:22,7225,3,0,1,8.0,...,0.452701,0.708478,0.454477,0.688360,0.463164,2.0,3,0.666667,-1,2
3,0,A060001004,A060000001,1,2020-03-24 00:17:29,7225,3,0,1,7.0,...,0.452701,0.708478,0.454477,0.663597,0.472479,3.0,4,0.750000,-1,3
4,0,A060001005,A060000001,1,2020-03-24 00:17:36,7225,3,0,1,7.0,...,0.452701,0.708478,0.454477,0.599375,0.490026,4.0,5,0.800000,-1,4
5,0,A060001007,A060000001,1,2020-03-24 00:17:47,7225,3,0,1,11.0,...,0.452701,0.708478,0.454477,0.515853,0.499750,5.0,6,0.833333,-1,5
6,0,A060003001,A060000003,0,2020-03-26 05:52:03,7226,3,5,3,0.0,...,0.452701,0.627090,0.483591,0.749694,0.433190,6.0,7,0.857143,-1,6
7,0,A060003002,A060000003,1,2020-03-26 05:52:10,7226,3,5,3,7.0,...,0.452701,0.627090,0.483591,0.720312,0.448847,6.0,8,0.750000,-1,6
8,0,A060003003,A060000003,1,2020-03-26 05:53:14,7226,3,5,3,64.0,...,0.452701,0.627090,0.483591,0.688360,0.463164,7.0,9,0.777778,-1,7
9,0,A060003004,A060000003,1,2020-03-26 05:53:29,7226,3,5,3,15.0,...,0.452701,0.627090,0.483591,0.663597,0.472479,8.0,10,0.800000,-1,8

In [53]:
def abc(x):
    if x > 10:
        return 10
    else:
        return x
    
df['abc'] = df.user_total_answer.apply(lambda x:abc(x))
df['recAccuracy'] = df['recCount']/df['abc']
df = df.drop(['abc'], axis=1)

In [81]:
def fe3(df):
    df['recAccuracy'] = -1

    group = df.groupby("userID")

    def set_rec_count(group):
        group.sort_values(by='Timestamp', axis=0, inplace=True)
        recAccuracy = group['answerCode'].rolling(10, min_periods=1).sum().shift(1)
        group['recCount'] = recAccuracy

        return group

    df['recCount'] = 0

    group = df.groupby("userID")

    group = group.apply(set_rec_count)
    group.reset_index(drop=True, inplace=True)

    df['recCount'] = group['recCount']
    df['recCount']= df['recCount'].fillna(0)
    df['recCount'] = df['recCount'].astype(int)
    
    def abc(x):
        if x > 10:
            return 10
        else:
            return x
    
    df['abc'] = df.user_total_answer.apply(lambda x:abc(x))
    df['recAccuracy'] = df['recCount']/df['abc']
    df = df.drop(['abc'], axis=1)
    
    return test
    
test = fe3(test)
test

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,elapsed,...,ass1_mean,ass1_std,ass2_mean,ass2_std,user_correct_answer,user_total_answer,user_acc,recAccuracy,recCount,abc
0,3,A050023001,A050000023,1,2020-01-09 10:56:31,2626,1,10,3,0.0,...,0.613659,0.486924,0.749694,0.433190,0.0,1,0.000000,0.000000,0,1
1,3,A050023002,A050000023,1,2020-01-09 10:56:57,2626,1,10,3,26.0,...,0.613659,0.486924,0.720312,0.448847,1.0,2,0.500000,0.500000,1,2
2,3,A050023003,A050000023,0,2020-01-09 10:58:31,2625,1,10,3,94.0,...,0.613659,0.486924,0.688360,0.463164,2.0,3,0.666667,0.666667,2,3
3,3,A050023004,A050000023,0,2020-01-09 10:58:36,2625,1,10,3,5.0,...,0.613659,0.486924,0.663597,0.472479,2.0,4,0.500000,0.500000,2,4
4,3,A050023006,A050000023,0,2020-01-09 10:58:43,2623,1,10,3,7.0,...,0.613659,0.486924,0.556891,0.496754,2.0,5,0.400000,0.400000,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260109,7439,A040130001,A040000130,0,2020-10-14 23:07:23,8832,10,23,2,0.0,...,0.608201,0.488169,0.749694,0.433190,8.0,12,0.666667,0.700000,7,10
260110,7439,A040130002,A040000130,1,2020-10-14 23:07:41,8832,10,23,2,18.0,...,0.608201,0.488169,0.720312,0.448847,8.0,13,0.615385,0.600000,6,10
260111,7439,A040130003,A040000130,1,2020-10-14 23:08:02,8244,10,23,2,21.0,...,0.608201,0.488169,0.688360,0.463164,9.0,14,0.642857,0.600000,6,10
260112,7439,A040130004,A040000130,1,2020-10-14 23:09:31,8244,10,23,2,89.0,...,0.608201,0.488169,0.663597,0.472479,10.0,15,0.666667,0.600000,6,10
260113,7439,A040130005,A040000130,-1,2020-10-14 23:10:03,8832,10,23,2,32.0,...,0.608201,0.488169,0.599375,0.490026,11.0,16,0.687500,0.700000,7,10

In [84]:
test = test.drop(['abc'], axis=1)

In [85]:
test.columns

Index(['userID', 'assessmentItemID', 'testId', 'answerCode', 'Timestamp',
       'KnowledgeTag', 'month', 'hour', 'week', 'elapsed', 'elapsed_cate',
       'assessmentItemID0', 'assessmentItemID1', 'assessmentItemID2',
       'testId0', 'testId1', 'test0_mean', 'test0_std', 'test1_mean',
       'test1_std', 'tag_mean', 'tag_std', 'ass0_mean', 'ass0_std',
       'ass1_mean', 'ass1_std', 'ass2_mean', 'ass2_std', 'user_correct_answer',
       'user_total_answer', 'user_acc', 'recAccuracy', 'recCount'],
      dtype='object')

In [31]:
cate = ['KnowledgeTag', 'month', 'hour', 'week', 'elapsed_cate',
       'assessmentItemID0', 'assessmentItemID1', 'assessmentItemID2',
       'testId0', 'testId1', 'assessmentItemID0', 'testId1']

conti = ['elapsed', 'test0_mean', 'test0_std', 'test1_mean',
       'test1_std', 'tag_mean', 'tag_std', 'ass0_mean', 'ass0_std',
       'ass1_mean', 'ass1_std', 'ass2_mean', 'ass2_std', 'user_correct_answer',
       'user_total_answer', 'user_acc', 'recAccuracy', 'recCount']

alpha = ['assessmentItemID', 'testId']
for i in alpha:
    cate2label = {j:i for i,j in enumerate(df[i].unique())}
    df[i] = df[i].map(cate2label)
    
#df.to_csv('../../../data/pkj.csv', index=False)

In [33]:
import time
from datetime import datetime
def convert_time(s):
    timestamp = time.mktime(
        datetime.strptime(s, "%Y-%m-%d %H:%M:%S").timetuple()
    )
    return int(timestamp)

df['Timestamp'] = df.Timestamp.apply(convert_time)

In [88]:
test.to_csv('../../../data/test.csv', index=False)

In [93]:
df2[df2['userID'] == 3]

,Unnamed: 0,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,...,ass0_std,ass1_mean,ass1_std,ass2_mean,ass2_std,user_correct_answer,user_total_answer,user_acc,recAccuracy,recCount
1954,1954,3,A050023001,A050000023,1,2020-01-09 10:56:31,373,10,14,1,...,0.474013,0.613659,0.486924,0.749694,0.433190,0,1,1.000000,0.000000,0
1955,1955,3,A050023002,A050000023,1,2020-01-09 10:56:57,373,10,14,1,...,0.474013,0.613659,0.486924,0.720312,0.448847,1,2,1.000000,0.500000,1
1956,1956,3,A050023003,A050000023,0,2020-01-09 10:58:31,374,10,14,1,...,0.474013,0.613659,0.486924,0.688360,0.463164,2,3,0.666667,0.666667,2
1957,1957,3,A050023004,A050000023,0,2020-01-09 10:58:36,374,10,14,1,...,0.474013,0.613659,0.486924,0.663597,0.472479,2,4,0.500000,0.500000,2
1958,1958,3,A050023006,A050000023,0,2020-01-09 10:58:43,375,10,14,1,...,0.474013,0.613659,0.486924,0.556891,0.496754,2,5,0.400000,0.400000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2984,2984,3,A050133003,A050000133,1,2020-10-26 13:10:22,369,7,19,2,...,0.474013,0.654130,0.475667,0.688360,0.463164,713,1031,0.692532,0.600000,6
2985,2985,3,A050133004,A050000133,1,2020-10-26 13:12:11,369,7,19,2,...,0.474013,0.654130,0.475667,0.663597,0.472479,714,1032,0.692829,0.600000,6
2986,2986,3,A050133005,A050000133,1,2020-10-26 13:12:36,435,7,19,2,...,0.474013,0.654130,0.475667,0.599375,0.490026,715,1033,0.693127,0.600000,6
2987,2987,3,A050133006,A050000133,1,2020-10-26 13:12:52,435,7,19,2,...,0.474013,0.654130,0.475667,0.556891,0.496754,716,1034,0.693424,0.700000,7
2988,2988,3,A050133007,A050000133,0,2020-10-26 13:13:11,369,7,19,2,...,0.474013,0.654130,0.475667,0.515853,0.499750,717,1035,0.692754,0.800000,8

In [96]:
test = pd.read_csv('../../../data/test.csv')
test

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,elapsed,...,ass0_std,ass1_mean,ass1_std,ass2_mean,ass2_std,user_correct_answer,user_total_answer,user_acc,recAccuracy,recCount
0,3,A050023001,A050000023,1,2020-01-09 10:56:31,373,10,14,1,0.0,...,0.474013,0.613659,0.486924,0.749694,0.433190,0.0,1,0.000000,0.000000,0
1,3,A050023002,A050000023,1,2020-01-09 10:56:57,373,10,14,1,26.0,...,0.474013,0.613659,0.486924,0.720312,0.448847,1.0,2,0.500000,0.500000,1
2,3,A050023003,A050000023,0,2020-01-09 10:58:31,374,10,14,1,94.0,...,0.474013,0.613659,0.486924,0.688360,0.463164,2.0,3,0.666667,0.666667,2
3,3,A050023004,A050000023,0,2020-01-09 10:58:36,374,10,14,1,5.0,...,0.474013,0.613659,0.486924,0.663597,0.472479,2.0,4,0.500000,0.500000,2
4,3,A050023006,A050000023,0,2020-01-09 10:58:43,375,10,14,1,7.0,...,0.474013,0.613659,0.486924,0.556891,0.496754,2.0,5,0.400000,0.400000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260109,7439,A040130001,A040000130,0,2020-10-14 23:07:23,290,7,7,5,0.0,...,0.466378,0.608201,0.488169,0.749694,0.433190,8.0,12,0.666667,0.700000,7
260110,7439,A040130002,A040000130,1,2020-10-14 23:07:41,290,7,7,5,18.0,...,0.466378,0.608201,0.488169,0.720312,0.448847,8.0,13,0.615385,0.600000,6
260111,7439,A040130003,A040000130,1,2020-10-14 23:08:02,292,7,7,5,21.0,...,0.466378,0.608201,0.488169,0.688360,0.463164,9.0,14,0.642857,0.600000,6
260112,7439,A040130004,A040000130,1,2020-10-14 23:09:31,292,7,7,5,89.0,...,0.466378,0.608201,0.488169,0.663597,0.472479,10.0,15,0.666667,0.600000,6
260113,7439,A040130005,A040000130,-1,2020-10-14 23:10:03,290,7,7,5,32.0,...,0.466378,0.608201,0.488169,0.599375,0.490026,11.0,16,0.687500,0.700000,7

In [59]:
def __augmentation(df):
    cnt = pd.DataFrame(df.groupby('userID')['answerCode'].count())
    cnt.answerCode = cnt.answerCode//100
    i_cnt = cnt[cnt['answerCode'] >= 1]

    n_index = -1
    for i,j in enumerate(i_cnt.index):
        c = i_cnt.iloc[i].answerCode
        index = df[df['userID'] == j].index
        for k in range(2, c+2):
            ii = index[-k*100:-100*(k-1)]
            if len(ii) > 20:
                df.loc[ii, ['userID']] = n_index
                n_index -= 1
    return df

df = __augmentation(df)
df.to_csv('../../../data/pkj2.csv', index=False)

OSError: Cannot save file into a non-existent directory: '../../data'

In [78]:
for i in cate:
    cate2label = {j:i for i,j in enumerate(df[i].unique())}
    if i == 'month':
        print(cate2label)
        break

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,elapsed,...,ass0_std,ass1_mean,ass1_std,ass2_mean,ass2_std,user_correct_answer,user_total_answer,user_acc,recAccuracy,recCount
0,-7,A060001001,A060000001,1,2020-03-24 00:17:11,0,0,0,0,0.0,...,0.452701,0.708478,0.454477,0.749694,0.433190,1,1,1.000000,0.000000,0
1,-7,A060001002,A060000001,1,2020-03-24 00:17:14,1,0,0,0,3.0,...,0.452701,0.708478,0.454477,0.720312,0.448847,2,2,1.000000,0.500000,1
2,-7,A060001003,A060000001,1,2020-03-24 00:17:22,1,0,0,0,8.0,...,0.452701,0.708478,0.454477,0.688360,0.463164,3,3,1.000000,0.666667,2
3,-7,A060001004,A060000001,1,2020-03-24 00:17:29,1,0,0,0,7.0,...,0.452701,0.708478,0.454477,0.663597,0.472479,4,4,1.000000,0.750000,3
4,-7,A060001005,A060000001,1,2020-03-24 00:17:36,1,0,0,0,7.0,...,0.452701,0.708478,0.454477,0.599375,0.490026,5,5,1.000000,0.800000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2525951,7441,A030071005,A030000071,0,2020-06-05 06:50:21,667,3,22,4,24.0,...,0.457287,0.641616,0.479541,0.599375,0.490026,1,5,0.200000,0.200000,1
2525952,7441,A040165001,A040000165,1,2020-08-21 01:06:39,274,5,3,4,0.0,...,0.466378,0.709128,0.454192,0.749694,0.433190,2,6,0.333333,0.166667,1
2525953,7441,A040165002,A040000165,1,2020-08-21 01:06:50,274,5,3,4,11.0,...,0.466378,0.709128,0.454192,0.720312,0.448847,3,7,0.428571,0.285714,2
2525954,7441,A040165003,A040000165,1,2020-08-21 01:07:36,274,5,3,4,46.0,...,0.466378,0.709128,0.454192,0.688360,0.463164,4,8,0.500000,0.375000,3
2525955,7441,A040165004,A040000165,1,2020-08-21 01:08:49,274,5,3,4,73.0,...,0.466378,0.709128,0.454192,0.663597,0.472479,5,9,0.555556,0.444444,4

In [24]:
import random
import pandas as pd

df = pd.read_csv('../../../data/pkj.csv')
df = df.sort_values(by=["userID", "Timestamp"]).reset_index(drop=True)

def custom_train_test_split(df, ratio=0.8, split=True):
    
    users = list(zip(df['userID'].value_counts().index, df['userID'].value_counts()))
    random.shuffle(users)
    
    max_train_data_len = ratio*len(df)
    sum_of_train_data = 0
    user_ids =[]

    for user_id, count in users:
        sum_of_train_data += count
        if max_train_data_len < sum_of_train_data:
            break
        user_ids.append(user_id)


    train = df[df['userID'].isin(user_ids)]
    test = df[df['userID'].isin(user_ids) == False]

    #test데이터셋은 각 유저의 마지막 interaction만 추출
    test = test[test['userID'] != test['userID'].shift(-1)]
    return train, test

In [35]:
# 유저별 분리
train, test = custom_train_test_split(df)

# 사용할 Feature 설정
FEATS = [
       'KnowledgeTag', 'month', 'hour', 'week', 'elapsed', 'elapsed_cate',
       'assessmentItemID0', 'assessmentItemID1', 'assessmentItemID2',
       'testId0', 'testId1', 'test0_mean', 'test0_std', 'test1_mean',
       'test1_std', 'tag_mean', 'tag_std', 'ass0_mean', 'ass0_std', 'Timestamp',
       'ass1_mean', 'ass1_std', 'ass2_mean', 'ass2_std', 'assessmentItemID', 'testId',
       'user_total_answer',]

# # X, y 값 분리
y = train['answerCode']
X = train.drop(['answerCode'], axis=1)

y_test = test['answerCode']
test = test.drop(['answerCode'], axis=1)

In [36]:
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import StratifiedKFold
import joblib

lgb_train = lgb.Dataset(X[FEATS], y)
lgb_test = lgb.Dataset(test[FEATS], y_test)

In [37]:
model = lgb.train(
    {'objective': 'binary'}, 
    lgb_train,
    valid_sets=[lgb_test],
    verbose_eval=100,
    num_boost_round=10000,
    early_stopping_rounds=500,
)

preds = model.predict(test[FEATS])
acc = accuracy_score(y_test, np.where(preds >= 0.5, 1, 0))
auc = roc_auc_score(y_test, preds)

print(f'VALID AUC : {auc} ACC : {acc}\n')

/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Info] Number of positive: 1320806, number of negative: 699865
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.031773 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3382
[LightGBM] [Info] Number of data points in the train set: 2020671, number of used features: 27
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.653647 -> initscore=0.635110
[LightGBM] [Info] Start training from score 0.635110
Training until validation scores don't improve for 500 rounds
[100]	valid_0's binary_logloss: 0.604177
[200]	valid_0's binary_logloss: 0.59452
[300]	valid_0's binary_logloss: 0.588991
[400]	valid_0's binary_logloss: 0.584086
[500]	valid_0's binary_logloss: 0.581453
[600]	valid_0's binary_logloss: 0.576971
[700]	valid_0's binary_logloss: 0.574343
[800]	valid_0's binary_logloss: 0.571841
[900]	valid_0's binary_logloss: 0.571095
[1000]	valid_0's binary_logloss: 0.569545
[1100]	valid_0's binary_logloss: 0.56797
[1200]	valid_0's binary_logloss: 0.56626
[1300]	valid_0's binary_logloss: 0.565789
[1400]	valid_0's binary_logloss: 0.564905
[1500]	valid_0's binary_logloss: 0.564662
[1600]	valid_0's binary_logloss: 0.563687
[1700]	valid_0's binary_logloss: 0.56427
[1800]	valid_0's binary_logloss: 0.564033
[1900]	valid_0's binary_logloss: 0.562963
[2000]	valid_0's binary_logloss: 0.562659
[2100]	valid_0's binary_logloss: 0.562143
[2200]	valid_0's binary_logloss: 0.561406
[2300]	valid_0's binary_logloss: 0.560627
[2400]	valid_0's binary_logloss: 0.560778
[2500]	valid_0's binary_logloss: 0.560781
[2600]	valid_0's binary_logloss: 0.560185
[2700]	valid_0's binary_logloss: 0.560155
[2800]	valid_0's binary_logloss: 0.560603
[2900]	valid_0's binary_logloss: 0.560073
[3000]	valid_0's binary_logloss: 0.560278
[3100]	valid_0's binary_logloss: 0.560415
[3200]	valid_0's binary_logloss: 0.559982
[3300]	valid_0's binary_logloss: 0.559981
[3400]	valid_0's binary_logloss: 0.559867
[3500]	valid_0's binary_logloss: 0.559865
[3600]	valid_0's binary_logloss: 0.559453
[3700]	valid_0's binary_logloss: 0.559407
[3800]	valid_0's binary_logloss: 0.559138
[3900]	valid_0's binary_logloss: 0.5588
[4000]	valid_0's binary_logloss: 0.558798
[4100]	valid_0's binary_logloss: 0.558877
[4200]	valid_0's binary_logloss: 0.558871
[4300]	valid_0's binary_logloss: 0.55871
[4400]	valid_0's binary_logloss: 0.558098
[4500]	valid_0's binary_logloss: 0.557823
[4600]	valid_0's binary_logloss: 0.558108
[4700]	valid_0's binary_logloss: 0.557738
[4800]	valid_0's binary_logloss: 0.557722
[4900]	valid_0's binary_logloss: 0.557576
[5000]	valid_0's binary_logloss: 0.557733
[5100]	valid_0's binary_logloss: 0.558297
[5200]	valid_0's binary_logloss: 0.558413
Early stopping, best iteration is:
[4775]	valid_0's binary_logloss: 0.557423
VALID AUC : 0.785345119555646 ACC : 0.7143786597267404

In [20]:
sub

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,month,hour,week,elapsed,...,ass0_std,ass1_mean,ass1_std,ass2_mean,ass2_std,user_correct_answer,user_total_answer,user_acc,recAccuracy,recCount
1035,3,A050133008,A050000133,-1,2020-10-26 13:13:57,369,7,19,2,46.0,...,0.474013,0.654130,0.475667,0.455696,0.498037,717.0,1036,0.692085,0.8,8
1706,4,A070146008,A070000146,-1,2020-12-27 02:47:54,579,9,8,6,23.0,...,0.499527,0.752279,0.431712,0.455696,0.498037,465.0,671,0.692996,0.7,7
3023,13,A070111008,A070000111,-1,2020-12-27 04:35:09,549,9,2,6,8.0,...,0.499527,0.648153,0.477562,0.455696,0.498037,915.0,1317,0.694761,0.4,4
4283,17,A090064006,A090000064,-1,2020-10-30 05:48:37,849,7,1,4,75.0,...,0.497944,0.648541,0.477447,0.556891,0.496754,1031.0,1260,0.818254,1.0,10
4670,26,A060135007,A060000135,-1,2020-10-23 11:44:18,617,7,12,4,17.0,...,0.452701,0.646105,0.478193,0.515853,0.499750,293.0,387,0.757106,0.8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260052,7395,A040122005,A040000122,-1,2020-09-08 02:05:20,284,6,8,0,2.0,...,0.466378,0.673615,0.468908,0.599375,0.490026,7.0,24,0.291667,0.1,1
260067,7404,A030111005,A030000111,-1,2020-10-13 09:49:18,673,7,15,0,107.0,...,0.457287,0.648153,0.477562,0.599375,0.490026,7.0,15,0.466667,0.4,4
260082,7416,A050193004,A050000193,-1,2020-10-04 02:44:41,878,7,8,6,24.0,...,0.474013,0.772069,0.419529,0.663597,0.472479,7.0,15,0.466667,0.4,4
260097,7417,A050193004,A050000193,-1,2020-09-06 13:09:15,878,6,19,6,21.0,...,0.474013,0.772069,0.419529,0.663597,0.472479,2.0,15,0.133333,0.2,2
260113,7439,A040130005,A040000130,-1,2020-10-14 23:10:03,290,7,7,5,32.0,...,0.466378,0.608201,0.488169,0.599375,0.490026,11.0,16,0.687500,0.7,7

In [4]:
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import StratifiedKFold
import joblib
import pandas as pd
from tqdm import tqdm

In [13]:
test = pd.read_csv('../../../data/test.csv')
sub = test[test['answerCode'] == -1]

In [14]:
p = []

FEATS = [
       'KnowledgeTag', 'month', 'hour', 'week', 'elapsed', 'elapsed_cate',
       'assessmentItemID0', 'assessmentItemID1', 'assessmentItemID2',
        'tag_mean', 'tag_std', 'ass0_mean', 'ass0_std',
       'ass1_mean', 'ass1_std', 'ass2_mean', 'ass2_std',
       'user_total_answer']

for i in tqdm(range(5)):
    load_model = joblib.load(f'lgb_{i}.pkl')
    preds = load_model.predict(sub[FEATS])
    p.append(preds)

#preds = model.predict(sub[FEATS])

100%|██████████| 5/5 [00:00<00:00,  9.33it/s]

In [15]:
s = pd.read_csv('../output/submission.csv')
m = (p[0] + p[1] + p[2] + p[3] + p[4])/5
s['prediction'] = m

In [16]:
s.to_csv('../output/submission.csv', index=False)

In [17]:
s

      id  prediction
0      0    0.658878
1      1    0.711218
2      2    0.337688
3      3    0.758971
4      4    0.326644
..   ...         ...
739  739    0.015663
740  740    0.796572
741  741    0.780255
742  742    0.790516
743  743    0.525410

[744 rows x 2 columns]

In [10]:
s

      id  prediction
0      0    0.668864
1      1    0.748420
2      2    0.252497
3      3    0.914511
4      4    0.527725
..   ...         ...
739  739    0.000141
740  740    0.008707
741  741    0.012336
742  742    0.068808
743  743    0.001762

[744 rows x 2 columns]

In [7]:
from tqdm import tqdm

n_splits = 5
str_kf = StratifiedKFold(n_splits = n_splits)

y = df['answerCode']
X = df.drop(['answerCode'], axis=1)

for i, (train_index, test_index) in tqdm(enumerate(str_kf.split(X, y))):
    X_train, X_valid = X.loc[train_index], X.loc[test_index]
    y_train, y_valid = y.loc[train_index], y.loc[test_index]
    
    lgb_train = lgb.Dataset(X_train[FEATS], y_train)
    lgb_test = lgb.Dataset(X_valid[FEATS], y_valid)
    
    model = lgb.train(
        {'objective': 'binary'}, 
        lgb_train,
        valid_sets=[lgb_train, lgb_test],
        verbose_eval=1000,
        num_boost_round=20000,
        early_stopping_rounds=500,
    )

    preds = model.predict(X_valid[FEATS])
    acc = accuracy_score(y_valid, np.where(preds >= 0.5, 1, 0))
    auc = roc_auc_score(y_valid, preds)

    print(f'VALID AUC : {auc} ACC : {acc}\n')
    
    joblib.dump(model, f'lgb_{i}.pkl')

0it [00:00, ?it/s]/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Info] Number of positive: 1322870, number of negative: 697894
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.026835 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2617
[LightGBM] [Info] Number of data points in the train set: 2020764, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.654639 -> initscore=0.639492
[LightGBM] [Info] Start training from score 0.639492
Training until validation scores don't improve for 500 rounds
[1000]	training's binary_logloss: 0.502915	valid_1's binary_logloss: 0.522087
[2000]	training's binary_logloss: 0.488195	valid_1's binary_logloss: 0.516882
[3000]	training's binary_logloss: 0.477446	valid_1's binary_logloss: 0.515208
[4000]	training's binary_logloss: 0.468539	valid_1's binary_logloss: 0.514793
[5000]	training's binary_logloss: 0.460291	valid_1's binary_logloss: 0.514409
Early stopping, best iteration is:
[4595]	training's binary_logloss: 0.463525	valid_1's binary_logloss: 0.514375
VALID AUC : 0.7885261931610134 ACC : 0.7558829118434179

1it [04:29, 269.48s/it]/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Info] Number of positive: 1322870, number of negative: 697895
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.026458 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2617
[LightGBM] [Info] Number of data points in the train set: 2020765, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.654638 -> initscore=0.639490
[LightGBM] [Info] Start training from score 0.639490
Training until validation scores don't improve for 500 rounds
[1000]	training's binary_logloss: 0.504509	valid_1's binary_logloss: 0.514961
[2000]	training's binary_logloss: 0.489331	valid_1's binary_logloss: 0.509794
[3000]	training's binary_logloss: 0.478414	valid_1's binary_logloss: 0.507531
[4000]	training's binary_logloss: 0.469049	valid_1's binary_logloss: 0.506921
Early stopping, best iteration is:
[3620]	training's binary_logloss: 0.472232	valid_1's binary_logloss: 0.506786

2it [08:11, 255.14s/it]

VALID AUC : 0.7968681854094036 ACC : 0.7605915386457796

/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Info] Number of positive: 1322870, number of negative: 697895
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.026122 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2617
[LightGBM] [Info] Number of data points in the train set: 2020765, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.654638 -> initscore=0.639490
[LightGBM] [Info] Start training from score 0.639490
Training until validation scores don't improve for 500 rounds
[1000]	training's binary_logloss: 0.505107	valid_1's binary_logloss: 0.516247
[2000]	training's binary_logloss: 0.489655	valid_1's binary_logloss: 0.510024
[3000]	training's binary_logloss: 0.478681	valid_1's binary_logloss: 0.507718
[4000]	training's binary_logloss: 0.469644	valid_1's binary_logloss: 0.507002
[5000]	training's binary_logloss: 0.461333	valid_1's binary_logloss: 0.506827
Early stopping, best iteration is:
[4632]	training's binary_logloss: 0.464296	valid_1's binary_logloss: 0.506602
VALID AUC : 0.796214514907617 ACC : 0.7606786344174777

3it [12:43, 260.20s/it]/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Info] Number of positive: 1322871, number of negative: 697894
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.026056 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2617
[LightGBM] [Info] Number of data points in the train set: 2020765, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.654639 -> initscore=0.639492
[LightGBM] [Info] Start training from score 0.639492
Training until validation scores don't improve for 500 rounds
[1000]	training's binary_logloss: 0.504961	valid_1's binary_logloss: 0.512287
[2000]	training's binary_logloss: 0.48983	valid_1's binary_logloss: 0.506127
[3000]	training's binary_logloss: 0.479019	valid_1's binary_logloss: 0.503517
[4000]	training's binary_logloss: 0.469705	valid_1's binary_logloss: 0.502388
[5000]	training's binary_logloss: 0.461417	valid_1's binary_logloss: 0.501994
Early stopping, best iteration is:
[4848]	training's binary_logloss: 0.462621	valid_1's binary_logloss: 0.501888
VALID AUC : 0.8007568325274818 ACC : 0.7642792527974568

4it [17:28, 267.74s/it]/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Info] Number of positive: 1322871, number of negative: 697894
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.026189 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2617
[LightGBM] [Info] Number of data points in the train set: 2020765, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.654639 -> initscore=0.639492
[LightGBM] [Info] Start training from score 0.639492
Training until validation scores don't improve for 500 rounds
[1000]	training's binary_logloss: 0.504479	valid_1's binary_logloss: 0.517238
[2000]	training's binary_logloss: 0.489148	valid_1's binary_logloss: 0.511267
[3000]	training's binary_logloss: 0.478538	valid_1's binary_logloss: 0.509733
[4000]	training's binary_logloss: 0.469674	valid_1's binary_logloss: 0.509303
Early stopping, best iteration is:
[3945]	training's binary_logloss: 0.470094	valid_1's binary_logloss: 0.509278
VALID AUC : 0.793120181476388 ACC : 0.7593484444497229

5it [21:24, 256.85s/it]

In [20]:
df.groupby('elapsed')['answerCode'].mean().head(15)

elapsed
0.0     0.733047
1.0     0.250137
2.0     0.228616
3.0     0.229742
4.0     0.248046
5.0     0.327463
6.0     0.438584
7.0     0.547493
8.0     0.620089
9.0     0.670788
10.0    0.702393
11.0    0.729468
12.0    0.743903
13.0    0.749591
14.0    0.754887
Name: answerCode, dtype: float64